name: Ping Space to Keep Awake

on:
  schedule:
    - cron: '0 5 * * *'   # รันทุกวันเวลา 05:00 UTC (12:00 น. เวลาไทย)
  workflow_dispatch:       # ช่วยให้สามารถกดรันแบบ manual ได้เองบนหน้าเว็บ GitHub

jobs:
  ping:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Ping HF Space Details Page
        run: |
          curl -I -s -o /dev/null -w "%{http_code}" https://huggingface.co/spaces/atlez/bittle-sneaker
      
      - name: Ping HF Space Direct App Page
        run: |
          curl -I -s -o /dev/null -w "%{http_code}" https://atlez-bittle-sneaker.hf.space
